apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: horizon
    name: horizon
  spec:
    replicas: 1
    selector:
      app: horizon
      deploymentconfig: horizon
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: horizon
          deploymentconfig: horizon
      spec:
        containers:
        - image: horizon:latest
          name: horizon
          ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          resources: {}
        serviceAccount: sa-anyuid
        serviceAccountName: sa-anyuid
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - horizon
        from:
          kind: ImageStreamTag
          name: horizon:latest
          namespace: openshaft
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: horizon
    name: horizon
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: horizon
      deploymentconfig: horizon
  status:
    loadBalancer: {}
kind: List
metadata: {}
