---

- name: Set Cinder Component
  set_fact:
    component: "cinder"

- name: Set Cinder Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ cinder_packages }}"

- name: Configure Cinder
  template:
    src: "cinder/cinder.conf.{{ common.version }}"
    dest: "{{ rootdir }}/cinder.conf"
  register: configure_cinder

- name: Create Cinder Startfile
  template:
   src: "cinder/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"

- name: Create Cinder Dockerfile
  template:
    src: "cinder/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: create_dockerfile
 
- name: Build Cinder image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_cinder.changed or create_dockerfile.changed
