---

- name: Set Cinder Component
  set_fact:
    component: "cinder"

- include: sandbox.yml

- name: Set Cinder Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ cinder_packages }}"

- name: Configure Cinder
  template:
    src: "cinder/cinder.conf.{{ common.version }}"
    dest: "{{ rootdir }}/cinder.conf"
  register: configure_cinder

- name: Create Cinder Startfile
  template:
   src: "cinder/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Cinder Dockerfile
  template:
    src: "cinder/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile
 
- name: Build Cinder Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_cinder.changed or start_file.changed or dockerfile.changed

- name: Set Cinder ConfigFiles For Openshift Config Maps
  set_fact:
    configfiles:
     - cinder.conf

- include: openshift.yml
  when: registry_url is defined and registry_certificate is defined and openshift_project is defined and configure_cinder.changed
