---

- name: Set Glance Component
  set_fact:
    component: "glance"

- include: sandbox.yml

- name: Set Glance Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ glance_packages }}"

- name: Configure Glance
  template:
    src: "glance/glance-{{ item }}.conf.{{ common.version }}"
    dest: "{{ rootdir }}/glance-{{ item }}.conf"
  with_items:
   - 'api'
   - 'registry'
  register: configure_glance

- name: Create Glance Startfile
  template:
   src: "glance/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Glance Dockerfile
  template:
    src: "glance/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile
 
- name: Build Glance Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_glance.changed or start_file.changed or dockerfile.changed

- name: Set Glance Config Files For Openshift Config Maps
  set_fact:
    configfiles:
     - glance-api.conf
     - glance-registry.conf

- include: openshift.yml
  when: registry_url is defined and registry_certificate is defined and openshift_project is defined and configure_glance.changed
