---

- name: Set Glance Component
  set_fact:
    component: "glance"

- name: Set Glance Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ glance_packages }}"

- name: Configure Glance
  template:
    src: "glance/glance-{{ item }}.conf.{{ common.version }}"
    dest: "{{ rootdir }}/glance-{{ item }}.conf"
  with_items:
   - 'api'
   - 'registry'
  register: configure_glance

- name: Create Glance Startfile
  template:
   src: "glance/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"

- name: Create Glance Dockerfile
  template:
    src: "glance/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: create_dockerfile
 
- name: Build Glance image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_glance.changed or create_dockerfile.changed
