---

- name: Set Heat Component
  set_fact:
    component: "heat"

- include: sandbox.yml

- name: Set Heat Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ openstack_packages + heat_packages }}"

- name: Configure Heat
  template:
    src: "heat/heat.conf.{{ common.version }}"
    dest: "{{ rootdir }}/heat.conf"
  register: configure_heat

- name: Create Heat Startfile
  template:
   src: "heat/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Heat Dockerfile
  template:
    src: "heat/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile
 
- name: Build Heat Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_heat.changed or start_file.changed or dockerfile.changed

- include: openshift.yml
  when: registry_url is defined and registry_certificate is defined and openshift_project is defined
