---

- name: Set Horizon Component
  set_fact:
      component: "horizon"

- include: sandbox.yml

- name: Set Horizon Prefix
  set_fact:
      rootdir: "{{ openshaft.rootdir }}/{{ component }}"
      packages: "{{ openstack_packages + horizon_packages }}"

- name: Configure Horizon
  template:
    src: "horizon/local_settings"
    dest: "{{ rootdir }}/local_settings"
  register: configure_horizon

- name: Create Horizon Startfile
  template:
    src: "horizon/start.sh.j2"
    dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Horizon Dockerfile
  template:
    src: "horizon/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile

- name: Build Horizon Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_horizon.changed or start_file.changed or dockerfile.changed

- name: Set Horizon ConfigFiles For Openshift Config Maps
  set_fact:
    configfiles:
     - local_settings

- include: openshift.yml
  when: registry_url is defined and registry_certificate is defined and openshift_project is defined  and configure_horizon.changed
