- include: variables.yml
  tags:
   - sandbox
   - dbupgrader
   - ceilometer
   - cinder
   - cinder-volume
   - compute
   - glance
   - heat
   - horizon
   - keystone
   - neutron
   - neutron-agents
   - neutron-dhcp
   - neutron-l3
   - neutron-ovs
   - nova
   - nova-compute
   - swift
   - swift-storage

- include: dbupgrader.yml
  tags:
   - dbupgrader

- include: keystone.yml
  tags:
   - keystone

- include: glance.yml
  tags:
   - glance

- include: cinder.yml
  tags:
   - cinder

- include: cinder-volume.yml
  tags:
   - cinder-volume

- include: neutron.yml
  tags:
   - neutron

- include: neutron-agents.yml
  tags:
   - neutron-agents

- include: nova.yml
  tags:
   - nova

- include: nova-compute.yml
  tags:
   - nova-compute

- include: heat.yml
  tags:
   - heat

- include: horizon.yml
  tags:
   - horizon

- include: swift.yml
  tags:
   - swift

- include: swift-storage.yml
  tags:
   - swift-storage
#
#- include: ceilometer.yml
#  tags:
#   - ceilometer
#
#
