---

- name: Install Neutron L3 Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ neutron_packages }}"

- name: Configure Neutron L3 Agent
  template:
    src: "l3_agent.ini.{{ version }}"
    dest: "/etc/neutron/l3_agent.ini"
    backup: yes
  notify:
   - Restart Neutron L3

- name: Configure Neutron L3 Metadata
  template:
    src: "metadata_agent.ini.{{ version }}"
    dest: "/etc/neutron/metadata_agent.ini"
    backup: yes
  notify:
   - Restart Neutron Metadata

- name: Enable Neutron L3 Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ neutron_l3_services }}"
  when: ansible_connection != 'docker'
