---

- name: Set Neutron Component
  set_fact:
    component: "neutron"

- include: sandbox.yml

- name: Set Neutron Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ neutron_packages }}"

- name: Configure Neutron
  template:
    src: "neutron/neutron.conf.{{ common.version }}"
    dest: "{{ rootdir }}/neutron.conf"
  register: configure_neutron

- name: Configure Neutron M2l Plugin File
  template:
    src: "neutron/ml2/ml2_conf.ini"
    dest: "{{ rootdir }}/ml2_conf.ini"
  when: neutron_core_plugin == 'ml2'

- name: Create Neutron Startfile
  template:
   src: "neutron/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Neutron Dockerfile
  template:
    src: "neutron/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile
 
- name: Build Neutron Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_neutron.changed or start_file.changed or dockerfile.changed

- include: openshift.yml
  when: registry_url is defined and registry_certificate is defined and openshift_project is defined
