---

- name: Set Nova Component
  set_fact:
    component: "nova"

- name: Set Nova Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ openstack_packages + nova_packages }}"

- name: Add Iptables Dummy File
  template:
    src: "nova/iptables-dummy"
    dest: "{{ rootdir }}/iptables-dummy"

- name: Configure Nova
  template:
    src: "nova/nova.conf.{{ version }}"
    dest: "{{ rootdir }}/nova.conf"
  register: configure_nova

- name: Create Nova Startfile
  template:
   src: "nova/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Nova Dockerfile
  template:
    src: "nova/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile

- name: Build Nova Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}"
  when: configure_nova.changed or start_file.changed or dockerfile.changed
