---

- name: Set Nova Compute Component
  set_fact:
    component: "nova-compute"

- include: sandbox.yml

- name: Set Nova Compute Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ openstack_packages + nova_compute_packages + neutron_packages }}"

- name: Set Nova Compute Ceilometer Packages
  set_fact:
    packages: "{{ openstack_packages + nova_compute_packages + neutron_packages + nova_compute_ceilometer_packages }}"
  when: nova_ceilometer

- name: Create Neutron Agents Ovs ifcfg-br-int
  template:
    src: "neutron/ifcfg-br-int"
    dest: "{{ rootdir }}/ifcfg-br-int"

- name: Configure Neutron Agents
  template:
    src: "neutron/neutron.conf.{{ version }}"
    dest: "{{ rootdir }}/neutron.conf"
  register: configure_neutron_agents

- name: Configure Neutron Agents Ovs
  template:
    src: "neutron/openvswitch/plugin.ini"
    dest: "{{ rootdir }}/plugin.ini"
  register: configure_neutron_agents_ovs

- name: Add Iptables Dummy File
  template:
    src: "nova/iptables-dummy"
    dest: "{{ rootdir }}/iptables-dummy"

- name: Configure Nova Compute
  template:
    src: "nova/nova.conf.{{ version }}"
    dest: "{{ rootdir }}/nova.conf"
  register: configure_nova_compute

- name: Create Nova Compute Startfile
  template:
   src: "nova/start_compute.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Nova Compute Dockerfile
  template:
    src: "nova/Dockerfile_compute.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile

- name: Build Nova Compute Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}"
  when: configure_neutron_agents.changed or configure_neutron_agents_ovs.changed or configure_nova_compute.changed or start_file.changed or dockerfile.changed

- include: openshift.yml
  when: registry_url is defined and registry_certificate is defined and openshift_project is defined
