---

- name: Create Base Sandbox
  file:
    path: "{{ openshaft.rootdir }}"
    state: directory
    mode: 0755

- name: Create Component Sandbox
  file:
    path: "{{ openshaft.rootdir }}/{{ component }}"
    state: directory
    mode: 0755

- name: Create Common Keystone Client File
  template:
    src: keystonerc_admin.j2
    dest: "{{ openshaft.rootdir }}/{{ component }}/keystonerc_admin"

- name: Create Common Keystone V3 Client File
  template:
    src: keystonerc_admin_v3.j2
    dest: "{{ openshaft.rootdir }}/{{ component }}/keystonerc_admin_v3"
