---

- name: Set Swift Component
  set_fact:
    component: "swift"

- include: sandbox.yml

- name: Set Swift Prefix
  set_fact:
    rootdir: "{{ openshaft.rootdir }}/{{ component }}"
    packages: "{{ openstack_packages + swift_packages }}"

- name: Configure Swift
  template:
    src: "swift/proxy-server.conf"
    dest: "{{ rootdir }}/proxy-server.conf"
  register: configure_swift

- name: Create Swift Startfile
  template:
   src: "swift/start.sh.j2"
   dest: "{{ rootdir }}/start.sh"
  register: start_file

- name: Create Swift Dockerfile
  template:
    src: "swift/Dockerfile.j2"
    dest: "{{ rootdir }}/Dockerfile"
  register: dockerfile
 
- name: Build Swift Image
  command: "docker build --rm -t openshaft/{{ component }} {{ rootdir }}" 
  when: configure_swift.changed or start_file.changed or dockerfile.changed
