apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvregistry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    server: master
    path: /registry
