apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: cinder-volume
    name: cinder-volume
  spec:
    replicas: 1
    selector:
      app: cinder-volume
      deploymentconfig: cinder-volume
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: cinder-volume
          deploymentconfig: cinder-volume
      spec:
        containers:
        - image: cinder-volume:latest
          name: cinder-volume
          resources: {}
          securityContext: 
            privileged: true
        serviceAccount: sa-privileged
        serviceAccountName: sa-privileged
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - cinder-volume
        from:
          kind: ImageStreamTag
          name: cinder-volume:latest
          namespace: openshaft
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
