apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rabbit
    name: rabbit
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: rabbitmq:3-management
      from:
        kind: DockerImage
        name: rabbitmq:3-management
      generation: null
      importPolicy: {}
      name: 3-management
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rabbit
    name: rabbit
  spec:
    replicas: 1
    selector:
      app: rabbit
      deploymentconfig: rabbit
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: rabbit
          deploymentconfig: rabbit
      spec:
        containers:
        - env:
          - name: RABBITMQ_DEFAULT_PASS
            value: guest
          - name: RABBITMQ_DEFAULT_USER
            value: guest
          image: rabbitmq:3-management
          name: rabbit
          ports:
          - containerPort: 15671
            protocol: TCP
          - containerPort: 15672
            protocol: TCP
          - containerPort: 25672
            protocol: TCP
          - containerPort: 4369
            protocol: TCP
          - containerPort: 5671
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbit-volume-1
        volumes:
        - emptyDir: {}
          name: rabbit-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rabbit
        from:
          kind: ImageStreamTag
          name: rabbit:3-management
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rabbit
    name: rabbit
  spec:
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5671-tcp
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 15671-tcp
      port: 15671
      protocol: TCP
      targetPort: 15671
    - name: 15672-tcp
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: 25672-tcp
      port: 25672
      protocol: TCP
      targetPort: 25672
    selector:
      app: rabbit
      deploymentconfig: rabbit
  status:
    loadBalancer: {}
kind: List
metadata: {}
