apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: swift
    name: swift
  spec:
    replicas: 1
    selector:
      app: swift
      deploymentconfig: swift
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: swift
          deploymentconfig: swift
      spec:
        containers:
        - image: swift:latest
          name: swift
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        serviceAccount: sa-anyuid
        serviceAccountName: sa-anyuid
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - swift
        from:
          kind: ImageStreamTag
          name: swift:latest
          namespace: openshaft
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: swift
    name: swift
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: swift
      deploymentconfig: swift
  status:
    loadBalancer: {}
kind: List
metadata: {}
